const EventManager = new Phaser.Events.EventEmitter();
EventManager.Events = {
    MOVE_LEFT: "MOVE_LEFT",
    MOVE_RIGHT: "MOVE_RIGHT",
    STOP_MOVE: "STOP_MOVE",

    UPDATE_SCORE: "UPDATE_SCORE",
    UPDATE_WAVE_INFO: "UPDATE_WAVE_INFO",
    SHOP_COLLIDE_START: "SHOP_COLLIDE_START",
    SHOP_COLLIDE_FINISH: "SHOP_COLLIDE_FINISH",
    HOME_COLLIDE_START: "HOME_COLLIDE_START",
    HOME_COLLIDE_FINISH: "HOME_COLLIDE_FINISH",

    WAVE_START: "WAVE_START",
    WAVE_END: "WAVE_END",
    WAVE_COMPLETE: "WAVE_COMPLETE",

    SHOW_WIZZARD_DIALOG: "SHOW_WIZZARD_DIALOG",
    SHOW_FANCY_TEXT: "SHOW_FANCY_TEXT",
};

export default EventManager;